name: screenshot-and-visitor

on:
  push:
    branches: [main, master]
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:
    inputs:
      add_like:
        description: 'Add your like (only one per user allowed)'
        required: false
        default: true
        type: boolean

permissions:
  contents: write
  pages: read
  actions: read

env:
  BADGE_STYLE: 'for-the-badge'
  BADGE_COLOR: 'brightgreen'
  LIKES_COLOR: 'gold'
  DATA_DIR: 'assets/db'
  SCREENSHOT_DIR: 'assets'

jobs:
  update-readme-and-visitor:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: '20.x'
      PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'false'

    steps:
      - name: 🔥 Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: 🔍 Check if sections are commented
        run: |
          # Перевіряємо чи закоментована секція скріншоту
          if grep -q "^[[:space:]]*<!--.*📸 Скріншот проекту" README.md || grep -q "^[[:space:]]*<!--.*📸 Latest Screenshot" README.md; then
            echo "📸 Screenshot section is commented out - skipping generation"
            echo "SCREENSHOT_SKIP=true" >> $GITHUB_ENV
          else
            echo "📸 Screenshot section is active - proceeding with generation"
            echo "SCREENSHOT_SKIP=false" >> $GITHUB_ENV
          fi

          # Перевіряємо чи закоментована секція статистики
          if grep -q "^[[:space:]]*<!--.*📊 Статистика GitHub" README.md || grep -q "^[[:space:]]*<!--.*📊 GitHub Statistics" README.md; then
            echo "📊 Stats section is commented out - skipping generation"
            echo "STATS_SKIP=true" >> $GITHUB_ENV
          else
            echo "📊 Stats section is active - proceeding with generation"
            echo "STATS_SKIP=false" >> $GITHUB_ENV
          fi

      - name: 🚀 Initialize workflow
        run: |
          DATA_DIR="$DATA_DIR"
          SCREENSHOT_DIR="$SCREENSHOT_DIR"
          mkdir -p "$DATA_DIR" "$SCREENSHOT_DIR"

          # Зберігаємо початковий вміст README
          cp README.md README_backup.md

          # Отримуємо вміст до і після автогенерованої секції
          awk '/<!-- AUTOGEN:STATS -->/{exit} {print}' README.md > README_before.tmp
          awk '/<!-- END:AUTOGEN -->/{found=1; next} found{print}' README.md > README_after.tmp

          # Створюємо тимчасовий README без автогенерованого вмісту
          {
            cat README_before.tmp
            echo "<!-- AUTOGEN:STATS -->"
            echo "🔄 Оновлення статистики..."
            echo "<!-- END:AUTOGEN -->"
            cat README_after.tmp
          } > README.md

          echo "🚀 Workflow initialized, README prepared for updates"

      - name: 📊 Collect all statistics
        run: |
          # [Існуючий код збору статистики залишається без змін]
          # Додайте тут весь ваш поточний код збору статистики

      - name: 🖥 Setup Node.js and dependencies
        run: |
          if [ "$SCREENSHOT_SKIP" = "true" ]; then
            echo "⏭️ Skipping Node.js setup - screenshot generation disabled"
            exit 0
          fi
          # [Існуючий код налаштування Node.js залишається без змін]

      - name: 📸 Generate screenshot from GitHub Pages
        run: |
          if [ "$SCREENSHOT_SKIP" = "true" ]; then
            echo "⏭️ Screenshot generation skipped - section is commented out"
            echo "SCREENSHOT_CREATED=false" >> $GITHUB_ENV
            exit 0
          fi
          # [Існуючий код генерації скріншоту залишається без змін]

      - name: 📝 Update README with all content
        run: |
          REPO_URL="https://raw.githubusercontent.com/${{ github.repository }}/${{ github.ref_name }}"
          TECH_BADGES=$(cat $DATA_DIR/tech-badges.txt 2>/dev/null || echo "")

          DOWNLOADS_BADGE=""
          if [ -f "$DATA_DIR/downloads-badge.json" ]; then
            DOWNLOADS_BADGE="[![⬇️ Downloads](https://img.shields.io/endpoint?url=$REPO_URL/$DATA_DIR/downloads-badge.json)](https://github.com/${{ github.repository }}/releases)"
          fi

          # Відновлюємо оригінальний README
          mv README_backup.md README.md

          # Отримуємо вміст до і після автогенерованої секції
          awk '/<!-- AUTOGEN:STATS -->/{exit} {print}' README.md > README_before.tmp
          awk '/<!-- END:AUTOGEN -->/{found=1; next} found{print}' README.md > README_after.tmp

          {
            cat README_before.tmp
            echo "<!-- AUTOGEN:STATS -->"
            
            # Додаємо технологічні бейджі тільки якщо секція не закоментована
            if [ "$STATS_SKIP" = "false" ]; then
              echo "$TECH_BADGES"
              echo ""
              echo "## 📊 Статистика GitHub :"
              echo ""
              echo "[![📊 Views](https://img.shields.io/endpoint?url=$REPO_URL/$DATA_DIR/visitors-badge.json)](https://github.com/${{ github.repository }}/graphs/traffic)"
              echo "[![⭐ Stars](https://img.shields.io/endpoint?url=$REPO_URL/$DATA_DIR/likes-badge.json)](https://github.com/${{ github.repository }}/actions/workflows/screenshot-and-visitor.yaml)"
              echo "[![📦 Size](https://img.shields.io/endpoint?url=$REPO_URL/$DATA_DIR/repo-size.json)](https://github.com/${{ github.repository }})"
              echo "[![📄 License](https://img.shields.io/endpoint?url=$REPO_URL/$DATA_DIR/repo-license.json)](https://github.com/${{ github.repository }}/blob/main/LICENSE)"
              if [ -n "$DOWNLOADS_BADGE" ]; then
                echo "$DOWNLOADS_BADGE"
              fi
            else
              echo "<!-- 📊 Статистика GitHub закоментована -->"
            fi
            
            # Додаємо скріншот тільки якщо секція не закоментована
            if [ "$SCREENSHOT_SKIP" = "false" ] && [ "$SCREENSHOT_CREATED" = "true" ] && [ -f "$SCREENSHOT_DIR/screenshot.png" ]; then
              SCREENSHOT_SIZE=$(stat -f%z "$SCREENSHOT_DIR/screenshot.png" 2>/dev/null || stat -c%s "$SCREENSHOT_DIR/screenshot.png" 2>/dev/null || echo "0")
              if [ "$SCREENSHOT_SIZE" -gt 0 ]; then
                echo ""
                echo "## 📸 Скріншот проекту"
                echo "![Project Screenshot](./$SCREENSHOT_DIR/screenshot.png)"
              fi
            else
              echo "<!-- 📸 Скріншот проекту закоментований -->"
            fi
            
            echo "<!-- END:AUTOGEN -->"
            cat README_after.tmp
          } > README.md

          rm -f README_before.tmp README_after.tmp
          echo "✅ README updated with all content"

      - name: 📤 Commit and deploy
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .

          COMMIT_MSG="📊 Auto-update: visitors, likes"
          if [ "$SCREENSHOT_CREATED" = "true" ]; then
            COMMIT_MSG="$COMMIT_MSG, and screenshot"
          fi

          git commit -m "$COMMIT_MSG" || exit 0
          git pull --rebase https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

          echo "✅ All updates completed successfully"